### ISSUE TITLE
(Maybe) Create flag for specs that can not be interpreted

### ISSUE THREAD

**Issue by jonaskrask** [overturetool/vdm-vscode#111]
Yeah, it's the spec. In the "old days" this would not have been executable, but it is trying to evaluate this:
```
exceptions_hd1_1:set of (Table_Co_ordinate) = let s:set of (Table_Co_ordinate) in s
```
If you look at the definition of Table_Co_ordinate, you'll see that it is a complex mix of product types and unions, but all of the components are finite types. So in theory this set can be evaluated, but ... it's enormous(!).
```
RelOrientation = <PERP> | <FACING> | <AWAY>;

OrientedExs = Exs_types * (RelOrientation | <NONE>)
inv mk_(exs,ro) ==
  not is_Storage_building(exs) <=> (ro = <NONE>);

OrientedPes = Pes_types * (RelOrientation | <NONE>)
inv mk_(pes,ro) ==
  pes <> <EARTHCOVEREDBUILDING> <=> (ro = <NONE>);

Table_Co_ordinate = OrientedExs * OrientedPes
```
So we know why... but perhaps we should do something, like add a deliberate error in the spec so that it fails early and leaves the user looking at a line that says, "This spec cannot be evaluated" or something?

Perhaps more generally, we could think about a flag that allows specs to be labelled as "do not interpret"?

_Originally posted by @nickbattle in https://github.com/jonaskrask/vdm-vscode/issues/76#issuecomment-1038887855_

**Comment by nickbattle** [comment]
This is partially fixed via the `vdmj.in.typebind_limit` property, which defaults to 100000. If you attempt a bind that is greater than this, you get a "quick fail" rather than a slow death by memory starvation.

**Comment by nickbattle** [comment]
Now the spec fails immediately (though I'm not sure why):
```
Default module is DEFAULT
Initialized in ...
java.lang.ArithmeticException: long overflow
Init terminated.

Session disconnected.
```

**Comment by nickbattle** [comment]
I've tidied this up a bit. Now it says, `Error 5040: Cannot evaluate type bind, size exceeds long` and stops at the line with the very large type bind. (The bind was so large that it could not even tell us how large it was, since the size exceeds 2^64!).

**Comment by nickbattle** [comment]
LOL... well, I had to try with the high precision build to see just how big this type actually is...
```
Error 5039: Cannot evaluate type bind of size 528294531135665246352339784916516606518847326036121522127960709026673902556724859474417255887657180000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 in 'DEFAULT' (./acs.vdmsl) at line 134:7
```
That's a big type :-)))

**Comment by nickbattle** [comment]
With a few more decimal places...
```
Error 5039: Cannot evaluate type bind of size 528294531135665246352339784916516606518847326036121522127960709026673902556724859474417255887657187894674394993257128678882347559502685537250538978462939576908386683999005084168731517676426441053024232908211188404148028292751561738838396898767036476489538580897737998336 in 'DEFAULT' (./acs.vdmsl) at line 134:7
```
