### ISSUE TITLE
POG error output

### ISSUE THREAD

**Issue by jonaskrask** [overturetool/vdm-vscode#114]
Example projects that output errors on POG:

**PP**
- [x] CashDispenserConcPP
- [ ] CashDispenserPP
- [ ] EnigmaPP
- [ ] MetroInterlockingPP
- [ ] MSAWconcurPP
- [ ] MSAWseqPP

**RT**

**Comment by nickbattle** [comment]
Gah! I thought I'd fixed all these. It looks like this one is because it's using unqualified type names, like "Date" rather than "Clock'Date". Hopefully that's not too hard to fix.

**Comment by nickbattle** [comment]
I've just pushed a fix to (VDMJ) development that fixes this.

**Comment by nickbattle** [comment]
I think this is fixed. Closing.
