### ISSUE TITLE
Refactor wiki

### ISSUE THREAD

**Issue by FrederikPM** [overturetool/vdm-vscode#143]
Refactor the wiki into two parts: user information and power-user information.

**Comment by nickbattle** [comment]
In case it isn't obvious, the idea here is to keep it as simple as possible for users who just want to use the tool as-provided to work with models, but also provide (elsewhere) information to the people who are interested to write their own format readers or their own analysis plugins and so on.

**Comment by nickbattle** [comment]
I did a lot of additional work on the wiki in the past few months, mainly for new starters. I think we can close this, as the current format is being improved all the time.
