### ISSUE TITLE
Group extension settings

### ISSUE THREAD

**Issue by FrederikPM** [overturetool/vdm-vscode#145]
Group extension settings in sub-menus.

**Comment by FrederikPM** [comment]
@nickbattle can you take a look at the grouping of the settings in this [VSIX](https://github.com/overturetool/vdm-vscode/actions/runs/2384243579) when you get the time. Besides the more obvious groupings from existing setting names I have moved some settings into a "development" group in an attempt to make the other groups less cluttered.
Any changes to the grouping can easily be made.

**Comment by nickbattle** [comment]
Yes, this is much better! We can move things around over time perhaps, though this grouping is sensible.

**Comment by FrederikPM** [comment]
Great. I'll merge it into development.
