### ISSUE TITLE
POG PO view ordering error

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#152]
When clicking expand all on POG window, it orders POs in a funny manner.

**Comment by nickbattle** [comment]
This seems OK in the 1.3.3 release candidate. The POs are always in numeric order.
Is there a small example that demonstrates this?

**Comment by leouk** [comment]
Ah, was on 1.3.2. Will try on newer version. On 1.3.2 any model with more than 10 POs.

**Comment by FrederikPM** [comment]
Hi @leouk. 
Is this still an issue?

**Comment by nickbattle** [comment]
We'll look again at this as part of the upgrade of the POG view. Closing this issue.
