### ISSUE TITLE
VSCode LSP getting out of synch

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#160]
I am getting some out-of-synch errors after the latest (VDMJ's dev branch setlinked to VSCode 1.3.3). 

I had a function like 

```
     f: PReal -> nat
     f(x) == floor x;
```

with a type named "PReal" (>=0) which I changed to "myreal" or the like, and removed the type definition of "PReal". The type checker then insistent that everywhere "myreal" was used was a type error. 

Refreshing wouldn't change the state, and neither would type+save. I had to hard reset the server (Developer: restart extension host) for things to go back. 

Reproducing this was "tricky", so there must be something else I am missing in the example above, but it hopefully will enable the discovery of the underlying problem..

**Comment by nickbattle** [comment]
Thanks for persevering with this. We need to get to the bottom of it, as it sounds quite serious. A few questions:

- A typecheck only happens on "save" (any file will do). Before this, you will continue to see errors for syntax as you type, and any "old" typecheck errors. But you shouldn't see any new TC errors until a save. You're saying these appear immediately when you save?
- Is there anything particular about the project(s) this happens in? Small, large, SL (I assume?), with/out annotations?
- Can you give the exact sequence (I know it's asking a lot!!), but it sounds like you had the spec above, all clean; then you changed f: PReal to f: myreal (if you save, that will give one error); then you renamed PReal to myreal (all the other PReals will then fail, but the f: myreal will clear); then you fixed the PReals to myreals, but those errors persisted over a save?
- I will try to reproduce with this example now, but then I'll be away until Monday afternoon.
- Lastly, there is a VSCode setting called "Server: Log Level". Can you try to catch this in these logs? The Settings page has a link to where the file will be created. (set the level to "all", though note that this can dump a LOT of logs, so remember to turn it off again!)

**Comment by nickbattle** [comment]
Well, I've just tried all the naive checks that I can think of with this spec (all in one file, with a "types" section added). But it is not giving any problems - you get the correct TC errors on save.

I'll try with some mult-file tests and perhaps multi-module, which may also be relevant? Is this type export/imported?

**Comment by nickbattle** [comment]
So I've tried multi-file mult-module with type imports renamed... and it's still fine.

You only see the problem _sometimes_, is that right? Usually it's fine? Or does a particular spec always exhibit the problem? (If the latter, please get a log as described above!!)

**Comment by leouk** [comment]
It's single file with named module. With explicit exports clauses (and non-struct) export types. 

It happens mostly when/around annotations (so far).

**Comment by leouk** [comment]
> Thanks for persevering with this. We need to get to the bottom of it, as it sounds quite serious. A few questions:
> 
> * A typecheck only happens on "save" (any file will do). Before this, you will continue to see errors for syntax as you type, and any "old" typecheck errors. But you shouldn't see any new TC errors until a save. You're saying these appear immediately when you save?

No. They "remain" after I made changes (or checked there were not problems). Even if I added a comment and saved, they then wouldn't go away. I tried adding expressions etc (to force a TC), but it wouldn't go away either. 

> * Is there anything particular about the project(s) this happens in? Small, large, SL (I assume?), with/out annotations?

SL, with annotation and high precision. It is relatively small 1000LOC, but has some involved invariants on reals, 
 
> * Can you give the exact sequence (I know it's asking a lot!!), but it sounds like you had the spec above, all clean; then you changed f: PReal to f: myreal (if you save, that will give one error); then you renamed PReal to myreal (all the other PReals will then fail, but the f: myreal will clear); then you fixed the PReals to myreals, but those errors persisted over a save?

So, I have spec is type checking. I changing one place to myreal; some type errors appear as myreal doesn't yet exist. I change all for myreal including the declaring site and save. The error remaining in few places - mostly steaming (if not entirely included in) annotations. Run VDMJ cmd line no errors. Had to restart the server for it to go away.  

> * I will try to reproduce with this example now, but then I'll be away until Monday afternoon.

Yes, it's difficult to reproduce. 

> * Lastly, there is a VSCode setting called "Server: Log Level". Can you try to catch this in these logs? The Settings page has a link to where the file will be created. (set the level to "all", though note that this can dump a LOT of logs, so remember to turn it off again!)

I found the log file, but wasn't sure what to look out for? Log level was finer, will put all.

**Comment by nickbattle** [comment]
If you have a log when this happens, send it to me!

**Comment by leouk** [comment]
I see. Will do. Wondered what to do! Now I know :-)

**Comment by nickbattle** [comment]
Ideally, create a log file for a new session where this occurs "early"... but I realise that might not be possible. But you can *stop* the session (ie. VSCode) log just after the problem appears, which will help (ie. I can look at the end).

**Comment by leouk** [comment]
I've put log all, then somehow the extension keeps crashing? It keeps saying that 

"
Unable to launch a debug session for the workspace folder AX without any VDM files
"

But there are VDM files there.

**Comment by nickbattle** [comment]
Hopefully this is nothing to do with the logging though? Does the problem disappear when you disable it?

The sync issue was to do with type checking. Are you able to get logs that show a sync issue - ie. before you attempt to launch anything?

**Comment by nickbattle** [comment]
Another thought about all this... You're on your Mac? Are you able to try the same model with VSCode on a different OS?

Some of the things you've described sound like a failure to notify the server of file changes at the client. That in part is related to OS filesystem support for file update events. I'm wondering whether this is partly to do with the OS. It would explain why I can't reproduce the same here (Linux).

**Comment by leouk** [comment]
Hum, only in lab, but otherwise all
Macs. I also just realised something else: laptop is ARM Mac, which apparently does have some issues with paths and env vars. 

The log problem was on laptop; Will try it on iMac shortly when back

**Comment by leouk** [comment]
Annoyingly I am now getting this on Laptop: the log for VDM contents were just.

Error: Could not find or load main class lsp.LSPServerSocket
Caused by: java.lang.ClassNotFoundException: lsp.LSPServerSocket

What could be wrong here? It was working well before. Not sure what's gone wrong.
[exthost.log](https://github.com/overturetool/vdm-vscode/files/8708319/exthost.log)
[7-VDM Tasks.log](https://github.com/overturetool/vdm-vscode/files/8708328/7-VDM.Tasks.log)

**Comment by leouk** [comment]
When trying to add server log on student machine (on windows), to get diagnostics for this, got this crash

![image](https://user-images.githubusercontent.com/1830337/202158679-3d4b46bf-c28c-4b19-bab3-e76c1cfe66ec.jpeg)

**Comment by nickbattle** [comment]
Looks like Windows is not working at the moment?? Is this linked to #194 perhaps?

**Comment by idhugoid** [comment]
Could it be the same anti-virus issue as reported here: https://github.com/microsoft/vscode/issues/137046?

**Comment by nickbattle** [comment]
@leouk Is this something you still have an "open" issue with?

**Comment by leouk** [comment]
I haven't had reports from students anymore. Will try this week when I am in the office.

**Comment by nickbattle** [comment]
@leouk And news on this?

**Comment by leouk** [comment]
Hi Nick. Not anymore, as students are not quite using it. But it seemed a Windows thing on a distributed installation/image. Sounded something to do with problems accessing directories in these circumstances, which shouldn't be a problem under ~/, but then I don't know where .vscode is on Windows.

**Comment by nickbattle** [comment]
Hmm, ok. Difficult to know what to do with this issue. If we close it, at last we will still have the evidence, if it happens again?

**Comment by leouk** [comment]
Guess, yes for now.
