### ISSUE TITLE
breakpoint versus @todo

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#162]
VSCode has a "tagging" mechanism when you have a --@todo in place. It adds a "bookmark" on the side of the line count. But that prevents the same line from having a breakpoint set. It gets quite confusing as I didn't know what the bookmark was. Only later did I realise the link between that and @todo. 

So I had to remove @todo to be able to add the breakpoint. I presume this might get other people too, so perhaps worth documenting?

**Comment by FrederikPM** [comment]
I'm not aware of a native "todo" feature in VSCode. But, I do know that there are multiple extensions that enables such a feature. Do you have one of those installed?

**Comment by leouk** [comment]
I see. I am not sure (haven't specifically added one). Thought it came with the recent (very nice) syntax highlighting multicolour for parenthesising. Might be with some extension. 

It basically puts a bookmark bow at the place where breakpoint red dot is, effectively blocking the option to add one on that line. 

It so happens the @todo was on the break line! Anyhow, thanks folks.

**Comment by nickbattle** [comment]
I think this can be closed.
