### ISSUE TITLE
Insistent error code for textDocument? 

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#164]
I am now constantly getting an error message when I start to type (and code completion appears)
  [Error - 1:37:03 PM] Request textDocument/completion failed.
    Message: 
    Code: -32603

It wasn't there before, and I have no idea why it appeared. Anyone knows how could I fix this?

**Comment by nickbattle** [comment]
Turn on logging and send me the trace. That's a good start. Does this happen for every spec or just one?

**Comment by nickbattle** [comment]
@leouk Have you seen this since? It may have been cleaned up with something else (I've never seen it!)

**Comment by leouk** [comment]
@nickbattle no, I haven't seen this anymore after 1.3.7 I think.

**Comment by nickbattle** [comment]
Can we close this then?

**Comment by leouk** [comment]
yep
