### ISSUE TITLE
Weird behaviour with MD files

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#169]
When I added a README.MD to a directory open in VSCode with VDM files, VSCode insisted in creating an empty README.MD.vdmsl? 

Is this something of my VSCode setup (like the @todo) or is this reproducible? Given how MD files are pervasive this might be annoying to users?

**Comment by nickbattle** [comment]
Ah yes, that probably would happen. Hmm. As a workaround, you can hopefully add the MD file to the ".vscode/vdmignore" file? The names in vdmignore are project-relative.

But I've just pushed something to "development" that should deal with this (you shouldn't now get an empty file). Can you try it? Or does this have to be high precision?

**Comment by leouk** [comment]
I pulled development and tried on without high precision (through set links having the new jar). Still got the same new file created, for Untitled.md got a Untitled.md.vdmsl as

```
--
-- Document created from Untitled.md at Tue May 24 13:03:20 BST 2022
--
```

Not particularly troublesome but a bit weird :-).

**Comment by nickbattle** [comment]
@leouk Can we close this one?
