### ISSUE TITLE
vdmignore (continued from issue #174)

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#176]
> Ugh, I can't remember the rules about whether `exports all` exports the type definition of the state record. I know it doesn't export the state fields or the "S" record value of that type.
> 
> You should be able to add the "target" folder to `.vscode/vdmignore` rather than using an ordering file. That's a bit easier to maintain and closer to what you really mean?
> 
> I can't see how an ordering file would affect this though. Strange. But unless I can reproduce it, I'm stuck :-(

I tried vdmignore but it didn't quite work. I originally had it in 

```
VDM_Toolkit/plugins/vdm2isa/.vscode/vdmignore
```

containing 

```./target``` or ```/target/```

but that fails with duplicate modules (for some files but not all)? It keeps getting in a kind of "loop" where it says it's okay, then says it isn't. I thought it was because of dangling ordering or vdmignore files somewhere but couldn't find any.  :-(. 

Any other suggestion?

**Comment by nickbattle** [comment]
You need one .vscode/vdmignore for each project that you open in VSCode.

**Comment by leouk** [comment]
Yes it does help. Effectively adding the extra .bscode/vdmignore at plugins (all three projects) solved it. 

But, it had to be "/target/" as "./target/" failed(?). This is now what I have in all three vdm2isa/vdmlib etc .vscode. Then plugins/.vscode/vdmignore has to also have 

/vdm2isa/target
/vdmlib/target
/AnnotationsVDMToolkit/target

Then all worked nicely.

Yes: this is a complicated scenario but a very important one. 

A key impediment for Overture development in Eclipse was exactly that kind of mixing of project styles and types being an impossible pain. In VSCode things work quite nicely :-)!

**Comment by leouk** [comment]
Things worked pretty well on one machine then I realised an issue on another machine. If in ./vscode/settings.json have

```
{
    "java.configuration.updateBuildConfiguration": "interactive"
}
```

The vdmignore with /target/ still gives the failures mentioned. I just then deleted the ..vscode/settings.json. When it's with "automatic" then vdmignore works. 

Don't know why but thought to mention.

**Comment by nickbattle** [comment]
I'm confused. That setting affects the Java extension for VSCode and controls when/whether it rebuilds the Java project when you modify pom.xml files (I googled it!). So you must have a VSCode project (ie. one folder tree) that contains a mixture of Java and VDM source and you want to work with both of them (ie. both VSCode language extensions) at the same time?

If the Java rebuild does a Maven "clean compile" or similar, the current target folder will be deleted and rebuilt. It's possible that that process somehow confuses the VDM file tracking.  If you can find a sequence of events that reliably produces the error, you could try turning on the "fine" server logging and let me see that?

**Comment by leouk** [comment]
Erm, yes :-). Java + VDM, that's where the vdmignores are. 

I have the vdm2isa + VDMToolkitAnnotations open, where the test files are .vdmsl, which then go to /target/*.vdmsl, hence the type checker error, and the vdmignore need. 

And by the way, now it's still with the duplicate modules issue, even without the settings.json in there. It seems that I can't open all three VDMToolkit plugins at once, but one at a time in separate VSCode projects, which isn't too bad (i.e. I was having the three projects + the top-level pom open, e.g. VSCode folder in VDM_Toolkit/plugins itself).

Will try and fine server log next.

**Comment by nickbattle** [comment]
Each VSCode project corresponds to one VDMJ command line invocation, in effect. All of the VDM sources for the dialect below that project folder are included in the file set to parse/check/run. So if you have multiple independent specifications under one root, it will try to load them all and any name clashes will be reported.

The VDM files are copied to the target by default as "resources", I would guess. You could modify this behaviour by looking at the maven-resources-plugin, where you can choose which files are actually copied over. There is an example in the VDMJ stdlib POM.

**Comment by leouk** [comment]
Ah, super! Yes. I see. I've actually took this over in vdmlib (from stdlib of course), but haven't added it to the other projects. Now I have and this solved things. Great. Still, knowing about the vdmignore is also quite useful.

**Comment by nickbattle** [comment]
Closing this as we've explained the issues and enhanced vdmignore since.
