### ISSUE TITLE
Debug hover on variables evaluates incorrectly when variable has a ' suffix

### ISSUE THREAD

**Issue by AaronBuhagiar** [overturetool/vdm-vscode#178]
Hi,

I noticed in the VSCode debugger tools when I hover over variables whose name ends with ', the context hover evaluates to the value of the variable without the '. The gif below shows this issue in action.

![vdm](https://user-images.githubusercontent.com/8428437/174131358-0e7f329f-65d8-423f-8880-066c13da73fc.gif)

**Comment by AaronBuhagiar** [comment]
Realised this is duplicated. If the

**Comment by AaronBuhagiar** [comment]
Noticed that this issue was already pointed out previously, however it seems that it has not yet made it to the current release of the extension on VSCode store. Is the fix available in the dev version?

**Comment by FrederikPM** [comment]
Hi,
There is a fix but it is not yet in the development version. However, it will be merged soon.
I will report back here when it has been merged.

**Comment by AaronBuhagiar** [comment]
Hi Frederik,

Thanks for the information

**Comment by FrederikPM** [comment]
Hi Aaron,
The fix has now been merged into development and will be part of the next release.
