### ISSUE TITLE
Can not Launch Run class

### ISSUE THREAD

**Issue by martinsekd** [overturetool/vdm-vscode#183]
Type: <b>Bug</b>

I get following error: 
>>[h] Did not receive a DAP port from the language server on start up, debugging is not activated <<
I have Java extension installed on VS code. I have Java version 1.8.0_341 on my PC. I have no errors marked in my VM project

Extension version: 1.3.4
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by nickbattle** [comment]
Strange. This error appears (where?) at startup, or when you start to debug?

It's possible that there is something new in 1.71.0 that's just come out. I will update and try that.

Meanwhile, can you show us the logs? (CTRL-SHIFT-P and select "Developer: Open Logs Folder"). Also, can you enable the LSP Server's logging (in the extension settings, set Server Log Level to "fine". There is a link to the log location there too).

**Comment by nickbattle** [comment]
I've just updated to 1.71.0 on Linux, and debugging seems fine.

**Comment by nickbattle** [comment]
Has this issue been resolved, or do you still need us to investigate?

**Comment by martinsekd** [comment]
No, it is fine now :-)

Den søn. 25. sep. 2022 kl. 23.00 skrev Nick Battle ***@***.***
