### ISSUE TITLE
Overture feature: real-time log viewer for RT specifications

### ISSUE THREAD

**Issue by nickbattle** [overturetool/vdm-vscode#43]
Execution of an RT specification produces a "log" file under generated/logs, which can be opened in a log file viewer that shows the execution and bus architecture of the model from various perspectives.

![Screenshot_20210303_132017](https://user-images.githubusercontent.com/1751423/109811867-40ee7100-7c23-11eb-8520-da4bcae1f0a2.png)

**Comment by nickbattle** [comment]
VDMJ produces the log files, but the graphical log viewer is part of Overture.

**Comment by nickbattle** [comment]
To start with this, we need a way to produce the log files under user control. I've created a LogCommand that is usable from the execution console, with the same semantics as the "log" command in command-line VDMJ. This then creates log files that we can potentially display with a subsequent UI tool.

[example.log](https://github.com/jonaskrask/vdm-vscode/files/7093854/example.log)

**Comment by nickbattle** [comment]
The location ("current working folder") of the Server is very confusing. We should perhaps set the working folder of each Server process to the root of the project that it is working with?

```
*
* VDMJ VDM_RT Interpreter
* DEBUG enabled
*

Default class is World
Initialized in ... 0.102 secs.

log example.log
RT events now logged to example.log

p new World().RunCSVScenario("VDM_IMM/scenario_B.csv")
= ()
Executed in 0.029 secs.

log
Flushing 15 RT events
RT events now logged to the console

log off
RT event logging disabled
```

**Comment by jonaskrask** [comment]
I would very much like to use the protocol to enable the feature, that way we don't really have to worry about the location of the server.
I was considering if we can utilize the "translate" message from SLSP, I see a way to use it albeit not really what it was intended for.. or we could create a new message, let me know what you think.

The way I would use the translate message is to make it cancelable, that way we can initialize the logging on the translate request, then hold back the response until the user "cancel"/stop the translation, which should result in a flush to the file and "log off". Though I am not sure how happy the client is to have the response pending like that..

**Comment by jonaskrask** [comment]
Never mind the above comment, I had misunderstood how the logging would work.

**Comment by jonaskrask** [comment]
Another option is to make the logging a run configuration option, like:
            "noDebug": false,
            "defaultName": null
Then we could make an option: "rtLog": bool. Which would create a log file in .generated/log/log-<datetime>.log
This leaves less margin for error in deciding where the file is stored and when the create a viewer we know where to look for the files

**Comment by nickbattle** [comment]
The problem is, ideally the logging needs to be on a per-execution basis rather than a per-session basis. That is why VDMJ's log command allows you to turn logging on and off around multiple calls, with different log filenames. The idea would be to get the system into a particular state, then enable logging, perform an operation call, and then turn logging off (or end the session, I suppose). But the point is that potentially each single execution is being logged separately.

With Overture, each launch configuration has an option to log real-time events, which isn't as flexible as the above.

Would it be possible to send a new "DAPX" (or SDAP?) message to a running DAP server when the client indicates somehow that they want to start/stop logging in a session? Otherwise... we're left with a command line option, though it could be more intelligent about generating the log filename automatically.

**Comment by jonaskrask** [comment]
From the looks of it we can easily send custom requests to the server. We just have to decide on command names and arguments.

Note to self: send the request to the active sessions if the session is of the VDM-RT type.

**Comment by nickbattle** [comment]
OK, that's good news. But we still have the problem of when to send such a log request, unless we just say that it has to cover the whole debugging session (as Overture does, but that's not as flexible as a command line that can log a few selected operations calls within a session).

**Comment by jonaskrask** [comment]
I was thinking we could create a button in the debug view that the use can press to activate/deactivate the logging

**Comment by FrederikPM** [comment]
@nickbattle I have started looking into to this building on Jonas' idea to simply add a button in the debug view enabling the user to signal start/stop logging during a VDMRT debug session.
It seems straight forward to send a custom request to the debug adapter containing the command name and any additional args. Would something like: `rtlog `as command name with the arg `start `or arg `stop` be fine?
As I understand it this would then enable the server to generate the log file which would then be located in a subfolder in `.generated` i guess.
If so then the next step would be for me to implement the graphical log viewer part.

**Comment by nickbattle** [comment]
I've just pushed a tweak to change it to use lastModifiedTime for both recording and comparison. Is that any better?

**Comment by nickbattle** [comment]
The LogCommand (ie. that you can issue in a debug session) is `Usage: log [<file> | off]`. If you omit the argument, logging is enabled and sent to the console, which isn't that useful. So I would say a command that sends a filename to enable it to write to that file, or no file which indicates that it should be disabled?

In terms of testing, you can generate a log file using the LogCommand during a session and then use the data you capture to test your display tool? (I mean you don't have to have the new LSPX message in place to get started).

But if you send a new message and describe it, I'll add a handler for it.

**Comment by FrederikPM** [comment]
Okay. Then I will send the command "log" with a filename as args to start the logging and then to stop the logging I will send the "log" command again but with "off" as args. Yes, I'll just use the existing LogCommand when I need something to test the UI with.

**Comment by FrederikPM** [comment]
@nickbattle did you implement a handler for the log message?
I'm finally at a point with the display tool where I more or less just need the command to work for the feature to be ready (for testing by you and Hugo if you guys have the time).

**Comment by nickbattle** [comment]
@FrederikPM No, it looks like I haven't implemented an LSP handler. There is just the "log" command (in the console) that you can use to generate files.

If you've implemented the Client side of this, can you show me a JSON message example. Then I can add a handler to write the log out to the location indicated.

**Comment by nickbattle** [comment]
I also need to know if this is going to be an extension to the DAP protocol or the LSP protocol. It only makes sense during execution, so presumably it's DAP? But then we have to be careful about when to send the log request, since it really only makes sense in a per-execution sense (ie. "trace this one print command"). So when would you send a DAP request if it isn't for a one-shot session?

The "log" command is crude,  but at least you can choose when to start/stop and interleave your print commands as you require.

**Comment by FrederikPM** [comment]
Yes, it is an extension to the DAP protocol.
The log JSON message would just enable the UI to present a button that the user could use during a vdm-rt debug session instead of writing the command in the debug console as it is now. Additionally, it would also enable the client to decide the location of the log file and the file extension. 
Using the command as it is now also works but for the log viewer tool to activate the log file that the user opens needs to have a specific file extension.

The JSON message to start logging would look like:
`{
 type: 'request',
 command: "log",
 arguments: <path>
}`
and to stop:
`{
 type: 'request',
 command: "log",
 arguments: "stop"
}`
Alternatively the stop message could just omit the arguments.

**Comment by nickbattle** [comment]
OK, that should be simple to implement. I'd recommend that we call the command "slsp/log" or "sdap/log", following the same convention that we have in LSP to indicate that it's an extension and avoid potential clashes if they introduce a "log" in DAP.

It's probably cleaner to omit the "arguments" to indicate that the log should be closed. We don't really need a way to send  the log to the console (the cmdline lets you do this, but it's not that useful).

Leave it with me... :-)
