### ISSUE TITLE
Go-to-Definition F12 faults

### ISSUE THREAD

**Issue by nickbattle** [overturetool/vdm-vscode#6]
There are several places where using "Go to Definition" does not find the definition. This issue is a place to list all of those that people find - I suggest we keep the issue open for a while, because new instances will be found as the tool is used. Please add anything you find as a comment below...

**Comment by nickbattle** [comment]
Polymorphic function types do not work with Go to Definition (F12). For example:
```
	setToSeq[@T]: set of @T +> seq of @T
	setToSeq(s) ==
		if s = {}
		then []
		else let e in set s in
			[e] ^ setToSeq[@T](s \ {e})     <-- F12 fails to find "T"
	measure card s;
```

**Comment by nickbattle** [comment]
Traces with type binds fail to locate the type with F12:
```
	SVInvariantTotal:
		let c : [Causality] in
		let v : [Variability] in
		let i : [Initial] in ...
```

**Comment by nickbattle** [comment]
Both polymorphic and type-bind F12 navigation now work (the problem was with all type binds, not just those within traces). The fix is currently in VDMJ 4.4.2-SNAPSHOT, but will get released into the official VDM VS Code build at some point.

**Comment by jonaskrask** [comment]
Available in release 1.0.3, removing tag if something else shows up

**Comment by nickbattle** [comment]
Object call designators are not locating correctly in 1.0.3 - for example `obj1.name(arg).field.op(123)` as an operation call. Most of the names in this will not locate, apart from the final op. This will be fixed (mostly) in 1.0.4, though names that resolve to local variables are proving difficult...

**Comment by nickbattle** [comment]
New object expressions were not working. This will be fixed in 1.0.4.

**Comment by paulch42** [comment]
Does not work on items in module imports and exports.

**Comment by paulch42** [comment]
Does not work in the body of a local function definition. Example
```
values val:nat = 10;

functions

eee:nat->nat
eee(n) == n;

fff:nat->nat
fff(n) == let ggg:nat->nat
              ggg(x) == val+eee(x),
              xxx = ggg(n*2)
          in xxx+val+ggg(4);
```
If fine when selecting `xxx`, `val` and `ggg` after the `in`. Also fine when selecting `ggg` in the definition of `xxx`. Fails when selecting `val` and `eee` in the body of `ggg`.

**Comment by nickbattle** [comment]
Thanks for these, Paul. I'll have a look tomorrow.

**Comment by paulch42** [comment]
Does not work in patterns. Example
```
types

NatPair :: m:nat n:nat;

functions

eee:NatPair->NatPair
eee(mk_NatPair(m,n)) == mk_NatPair(n,m);

fff:NatPair->NatPair
fff(np) == cases np:
             mk_NatPair(m,n) -> mk_NatPair(n,m)
           end;
```
In both cases all is fine in the expression, but selecting `mk_NatPair` in the patterns fails.

**Comment by nickbattle** [comment]
I've added import/exports - on imports, clicking on any name, including any rename, navigates to the definition (ie. in the exporting module); on exports, clicking on any name navigates to the definition within the current module. I suspect it won't work for the names of types in the signatures though. Will check. If you click on the *use* of an imported name, that already navigates to the import, which seems reasonable(?). So you can F12 once to get from a call to its import and then again to get from the import to the original definition.

Good spot with patterns! Usually patterns do not define navigable names (they *are* the definitions, in effect), but with mk_R patterns it seems reasonable to navigate to the type.

Haven't looked at the other cases yet, but keep 'em coming :-)

**Comment by nickbattle** [comment]
OK, these all seem to be working. Changes currently in "development" branch, but will be included in 1.0.5 at some point.

**Comment by nickbattle** [comment]
I noticed a few more missing F12 cases yesterday:

* is_ expressions worked with simple named types, but not with more complex types like "set of T"
* narrow_ expressions had the same problem as is_
* Types used in PatternBinds (that are actually type binds) didn't work
* The type arguments to function instantiations didn't work.

All of these are now working in development, ready for 1.0.5

**Comment by nickbattle** [comment]
Just fixed a few more cases:
- ext clauses didn't work
- same with errs clauses
- and so specification statements (with errs and ext clauses) also didn't work

Fixed now.

**Comment by nickbattle** [comment]
And just fixed navigation to field types in an SL state definition. This wasn't working, though init and inv clauses were OK.

**Comment by nickbattle** [comment]
A nasty case just appeared, where an F12 of an expression pattern causes the LSP server to crash. For example:
```
functions
	f: nat -> nat
	f(a) ==
		let mk_((a), b) = mk_(1, 2) in a + b;
```
Using F12 while on the `(a)` pattern causes the problem. It was a missing visitor set parameter in the related pattern visitor. Now fixed, and correctly navigates to the parameter definition of "a" on the line above.

**Comment by nickbattle** [comment]
I'm going to close this one now. We've not had any new problems for a while, and anything that pops up can create a new issue.
